// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublicaDesafioBackend.Models;

namespace PublicaDesafioBackend.Migrations
{
    [DbContext(typeof(ContextoJogo))]
    [Migration("20200920211944_inicio")]
    partial class inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PublicaDesafioBackend.Models.Jogo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<short>("MaximoTemporada")
                        .HasColumnType("smallint");

                    b.Property<short>("MinimoTemporada")
                        .HasColumnType("smallint");

                    b.Property<short>("Placar")
                        .HasColumnType("smallint");

                    b.Property<short>("QuebraRecordeMax")
                        .HasColumnType("smallint");

                    b.Property<short>("QuebraRecordeMin")
                        .HasColumnType("smallint");

                    b.HasKey("ID");

                    b.ToTable("Jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
