// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublicaDesafioBackend.Models;

namespace PublicaDesafioBackend.Migrations
{
    [DbContext(typeof(ContextoJogo))]
    partial class ContextoJogoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PublicaDesafioBackend.Models.Jogo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ushort>("MaximoTemporada")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("MinimoTemporada")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Placar")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("QuebraRecordeMax")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("QuebraRecordeMin")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("ID");

                    b.ToTable("Jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
