// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublicaDesafioBackend.Models;

namespace PublicaDesafioBackend.Migrations
{
    [DbContext(typeof(ContextoJogo))]
    partial class ContextoJogoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PublicaDesafioBackend.Models.Jogo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<short>("MaximoTemporada")
                        .HasColumnType("smallint");

                    b.Property<short>("MinimoTemporada")
                        .HasColumnType("smallint");

                    b.Property<int>("PessoaID")
                        .HasColumnType("int");

                    b.Property<short>("Placar")
                        .HasColumnType("smallint");

                    b.Property<short>("QuebraRecordeMax")
                        .HasColumnType("smallint");

                    b.Property<short>("QuebraRecordeMin")
                        .HasColumnType("smallint");

                    b.HasKey("ID");

                    b.HasIndex("PessoaID");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("PublicaDesafioBackend.Models.Pessoa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Senha")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.HasKey("ID");

                    b.ToTable("pessoas");
                });

            modelBuilder.Entity("PublicaDesafioBackend.Models.Jogo", b =>
                {
                    b.HasOne("PublicaDesafioBackend.Models.Pessoa", "Pessoa")
                        .WithMany("Jogos")
                        .HasForeignKey("PessoaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
